server:
  port: 8989

management:
  security:
    enabled: false
  context-path: /_admin


logging:
  level:
    root: info
#    org.springframework.integration: debug


#spring:
#  rabbitmq:
#    host: localhost

#eureka:
#  instance:
#    non-secure-port: ${management.port}
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/



