spring:
  rabbitmq:
    host: localhost
  cloud:
    bus:
      destination: bus

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#    restart:
#      enabled: false


eureka:
  instance:
#    hostname: localhost
#    non-secure-port: 80
    prefer-ip-address: true
#    status-page-url-path: ${management.context-path}/info
#    health-check-url-path: ${management.context-path}/health
#    home-page-url-path: ${management.context-path}/
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    region: region1
    serviceUrl:
      defaultZone: http://eureka:123456@peer1:8761/eureka,http://eureka:123456@peer2:8761/eureka,http://eureka:123456@peer3:8761/eureka
      zone1: http://eureka:123456@peer1:8761/eureka/
      zone2: http://eureka:123456@peer2:8761/eureka/
    prefer-same-zone-eureka: true
    availability-zones:
      region1: ${ACTIVE_ZONE:defaultZone}

    healthcheck:
      enabled: true

logging:
  config: ${LOGBACK_CONFIG:http://${security.user.name:}:${security.user.password:}@localhost:8888/${spring.application.name}/${spring.profiles.active:default}/${spring.cloud.config.label:master}/logback.xml}
  level:
    root: debug
    sun.net: info
    sun.rmi: info
    jdk.event: info
    javax.xml: info
    com.netflix.config: info
    com.netflix.eureka: off
    com.netflix.discovery: info
    com.netflix.loadbalancer: info
    com.sun.jersey: info
    org.apache.http: info
    org.apache.http.wire: info
    org.apache.http.headers: info
    org.apache.tomcat: info
    org.apache.coyote: info
    org.apache.catalina: info
    org.hibernate.validator: info
    org.springframework.beans: info
    org.springframework.boot: debug
    org.springframework.boot.autoconfigure: info
    org.springframework.boot.web: debug
    org.springframework.core: info
    org.springframework.cloud: debug
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: warn
    org.springframework.jmx: info
    org.springframework.web: debug
    org.springframework.web.client: info
    org.springframework.security: info