server:
  port: 9411

spring:
#  rabbitmq:
#    host: localhost

#spring:
#  cloud:
#    stream:
#      binders:
#        rabbit1:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost

  sleuth:
    enabled: false

zipkin:
  storage:
    type: mysql

