server:
  port: 9411

spring:
#  datasource:
#    url: jdbc:mysql://10.69.205.36:3306/meipro_zipkin?allowMultiQueries=true
#    username: meipro-dev
#    password: 123.gome
#    driver-class-name: com.mysql.jdbc.Driver

#  rabbitmq:
#    host: 10.69.205.36

#spring:
#  cloud:
#    stream:
#      binders:
#        rabbit1:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost
  sleuth:
    enabled: false
    stream:
      poller:
        max-messages-per-poll: 100
    stream:
      group: zipkin
  zipkin:
    sender:
      type: rabbit

zipkin:
  storage:
    type: mysql

