server:
  port: 9000


ribbon:
  EnableZoneExclusivity: true

provider:
  ribbon:
#    EnableZoneAffinity: false
    ServerListRefreshInterval: 1000

# For demo only allow more hystrix connections
hystrix:
  stream:
    maxConcurrentConnections: 20
    bus:
      enabled: true
management:
  server:
    servlet:
      context-path: /_admin
    port: 9001