info:
  applicationName: Microservice Provider
  description: Spring Cloud Samples

server:
  port: 5000
management:
  server:
    servlet:
      context-path: /_admin
    port: 5001

spring:
#  zipkin:
#    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
    stream:
      group: zipkin

#eureka:
#  instance:
#    metadata-map:
#      zone: activeZone

#eureka:
#  instance:
#    prefer-ip-address: true
#    metadata-map:
#      management.port: ${management.port}
