server:
  port: 5001

spring:
  zipkin:
    base-url: http://localhost:9411/
eureka:
  instance:
    metadata-map:
      zone: activeZone

#management:
#  port: 8991

#eureka:
#  instance:
#    prefer-ip-address: true
#    metadata-map:
#      management.port: ${management.port}
