info:
  applicationName: Microservice Provider
  description: Spring Cloud Samples

server:
  port: 5001
management:
#  port: 8991
  security:
    enabled: false
  context-path: /_admin

spring:
  zipkin:
#    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

#eureka:
#  instance:
#    metadata-map:
#      zone: activeZone

#eureka:
#  instance:
#    prefer-ip-address: true
#    metadata-map:
#      management.port: ${management.port}
