info:
  applicationName: Eureka Server
  description: Spring Cloud Samples

management:
  security:
    enabled: false # default true
  context-path: /_admin

eureka:
  datacenter: eureka
  environment: development
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2
#    status-page-url-path: ${server.context-path}/info
#    health-check-url-path: ${server.context-path}/health


#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 4000
#    wait-time-in-ms-when-sync-empty: 0
#    number-of-replication-retries: 0
#    enable-self-preservation: false
#    renewal-percent-threshold: 0.01

#  client:
#    register-with-eureka: false # Standalone Eureka Server
#    fetch-registry: false # Standalone Eureka Server
#    registry-fetch-interval-seconds: 1
#    initial-instance-info-replication-interval-seconds: 2
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  rabbitmq:
    host: localhost

logging:
  level:
    root: info
#    org.springframework.web: info
#    org.springframework.cloud: debug
#    com.netflix.discovery: 'off'


---
spring:
  profiles: standalone

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # Standalone Eureka Server
    fetch-registry: false # Standalone Eureka Server
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/

---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/

---
spring:
  profiles: peer3

server:
  port: 8763

eureka:
  instance:
    hostname: peer3
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
