info:
  applicationName: Eureka Server
  description: Spring Cloud Samples

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
#    prefer-ip-address: true
#    hostname: localhost
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2
#    status-page-url-path: ${server.context-path}/info
#    health-check-url-path: ${server.context-path}/health
    metadata-map:
      user: ${spring.security.user.name}
      password: ${spring.security.user.password}

  server:
    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 4000
#    wait-time-in-ms-when-sync-empty: 0
#    number-of-replication-retries: 0
#    enable-self-preservation: false
#    renewal-percent-threshold: 0.01

#  client:
#    register-with-eureka: false # Standalone Eureka Server
#    fetch-registry: false # Standalone Eureka Server
#    registry-fetch-interval-seconds: 1
#    initial-instance-info-replication-interval-seconds: 2
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  rabbitmq:
    host: localhost
  security:
    user:
      name: eureka
      password: 123456
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

---
spring:
  profiles: standalone

server:
  port: 8761

management:
  server:
    servlet:
      context-path: /_admin
    port: 8861

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false # Standalone Eureka Server
    fetch-registry: false # Standalone Eureka Server
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/

---
spring:
  profiles: peer1

server:
  port: 8761

management:
  server:
    servlet:
      context-path: /_admin
    port: 8861

eureka:
  instance:
    hostname: peer1

  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer2:8762/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@peer3:8763/eureka/

---
spring:
  profiles: peer2

server:
  port: 8762

management:
  server:
    servlet:
      context-path: /_admin
    port: 8862

eureka:
  instance:
    hostname: peer2

  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:8761/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@peer3:8763/eureka/

---
spring:
  profiles: peer3

server:
  port: 8763

management:
  server:
    servlet:
      context-path: /_admin
    port: 8863

eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:8761/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@peer2:8762/eureka/
