eureka:
  instance:
    prefer-ip-address: true
#    hostname: localhost
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2
#    status-page-url-path: ${server.context-path}/info
#    health-check-url-path: ${server.context-path}/health


#  server:
#    wait-time-in-ms-when-sync-empty: 0
#    number-of-replication-retries: 0
#    enable-self-preservation: false
#    renewal-percent-threshold: 0.01

  client:
    register-with-eureka: false # Standalone Eureka Server
    fetch-registry: false # Standalone Eureka Server
#    registry-fetch-interval-seconds: 1
#    initial-instance-info-replication-interval-seconds: 2
    service-url:
      defaultZone: http://localhost:8761/eureka/


#  dashboard:
#    path: /dashboard

spring:
  rabbitmq:
    host: localhost

logging:
  level:
    org.springframework.web: info
    org.springframework.cloud: debug
    com.netflix.discovery: 'off'


#---
#spring:
#  profiles: peer1
#eureka:
#  instance:
#    hostname: peer1
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/

#---
#spring:
#  profiles: peer2
#eureka:
#  instance:
#    hostname: peer2
#    prefer-ip-address: true
#
#  client:
#    service-url:
#      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
#---
#spring:
#  profiles: peer3
#eureka:
#  instance:
#    hostname: peer3
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
