info:
  applicationName: Microservice Consumer
  description: Spring Cloud Samples

server:
  port: 4000

management:
  server:
    servlet:
      context-path: /_admin
    port: 4001

spring:
#  zipkin:
#    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
    stream:
      group: zipkin
    scheduled:
      skip-pattern: org.springframework.cloud.netflix.hystrix.stream.HystrixStreamTask

# eureka.client.healthcheck.enabled=true should only be set in application.yml.
# Setting the value in bootstrap.yml causes undesirable side effects, such as registering in Eureka with an UNKNOWN status.
eureka:
  client:
    healthcheck:
      enabled: true
#  instance:
#    prefer-ip-address: true
#    metadata-map:
#      management.port: ${management.port}

#feign:
#  hystrix:
#    enabled: true

feign:
  httpclient:
    enabled: true

ribbon:
  ReadTimeout: 45000
  ConnectTimeout: 35000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 45000


