info:
  applicationName: Microservice Consumer
  description: Spring Cloud Samples

server:
  port: 5002

management:
  security:
    enabled: false
  context-path: /_admin


spring:
#  zipkin:
#    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

logging:
  level:
    root: info

#eureka:
#  instance:
#    prefer-ip-address: true
#    metadata-map:
#      management.port: ${management.port}

#eureka:
#  instance:
#    metadata-map:
#      zone: activeZone
#  client:
#    prefer-same-zone-eureka: true

#feign:
#  hystrix:
#    enabled: true


