info:
  applicationName: Config Server
  description: Spring Cloud Samples

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  server:
    servlet:
      context-path: /_admin
    port: 8889

eureka:
  client:
    # must be in application.yml or application.properties
    healthcheck:
      enabled: true

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.dir}/../config-repo
          fail-on-error: true
#        git:
#          uri: https://github.com/barryTT/spring-cloud-sample.git
#          search-paths: config-repo
#          basedir: target/config
#          clone-on-start: true
#          force-pull: true
      fail-fast: true
    bus:
      destination: bus

  rabbitmq:
    host: localhost
# To use the default Spring Boot configured HTTP Basic security, just include Spring Security on the classpath (e.g. through spring-boot-starter-security).
# The default is a username of "user" and a randomly generated password, which isn’t going to be very useful in practice,
# so we recommend you configure the password (via security.user.password) and encrypt it (see below for instructions on how to do that).
  security:
    user:
      name: config # Default user name
      password: password #default password
---
spring:
  profiles: standalone

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:123456@localhost:8761/eureka/

---
spring:
  profiles: cloud

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:123456@peer1:8761/eureka,http://eureka:123456@peer2:8761/eureka,http://eureka:123456@peer3:8761/eureka